const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  // The project folder name contains "(2)". Vue CLI's default copy-plugin ignore
  // rule for public/index.html is an ABSOLUTE glob path, and the "(" / ")" in the
  // folder name are treated as glob extglob syntax, so the rule fails to match.
  // That lets index.html be copied AND generated by HtmlWebpackPlugin, producing
  // "Multiple assets emit different content to the same filename index.html".
  // Add a path-independent ignore glob to reliably exclude it from the copy.
  chainWebpack: config => {
    config.plugin('copy').tap(args => {
      args[0].patterns[0].globOptions.ignore.push('**/index.html')
      return args
    })
  }
})
